# Generated by Django 2.2.5 on 2019-09-23 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='apt_building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('time_update', models.DateTimeField()),
                ('description', models.TextField()),
                ('amount_of_user', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='bike_company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('time_update', models.DateTimeField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='bike_video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('time_update', models.DateTimeField()),
                ('description', models.TextField()),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('subcription_date', models.DateTimeField()),
                ('rent_status', models.CharField(choices=[('K', 'KEEP'), ('R', 'RETURNED')], max_length=1)),
                ('rent_date', models.DateTimeField()),
                ('description', models.TextField()),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.apt_building')),
            ],
        ),
        migrations.CreateModel(
            name='toolbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toolbox_ID', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('time_update', models.DateTimeField()),
                ('description', models.TextField()),
                ('amount', models.IntegerField()),
                ('rent_status', models.CharField(choices=[('O', 'ON\xa0RENT'), ('R', 'RETURNED')], max_length=1)),
                ('building', models.ManyToManyField(blank=True, to='database.apt_building')),
                ('sponsor', models.ManyToManyField(blank=True, to='database.bike_company')),
                ('user_rent', models.ManyToManyField(blank=True, to='database.user')),
                ('video', models.ManyToManyField(to='database.bike_video')),
            ],
        ),
        migrations.CreateModel(
            name='tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('time_update', models.DateTimeField()),
                ('description', models.TextField()),
                ('amount', models.IntegerField(default=0)),
                ('quality', models.CharField(choices=[('G', 'Good'), ('B', 'Bad')], max_length=1)),
                ('toolbox', models.ManyToManyField(to='database.toolbox')),
                ('video', models.ManyToManyField(to='database.bike_video')),
            ],
        ),
    ]
