# Generated by Django 2.2.5 on 2019-10-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toolbox',
            name='category',
        ),
        migrations.AlterField(
            model_name='toolbox',
            name='rent_status',
            field=models.CharField(choices=[('K', 'KEEP'), ('R', 'RETURNED')], max_length=1),
        ),
    ]
