# Generated by Django 2.2.5 on 2019-10-29 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20191029_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toolbox',
            name='user_rent',
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
