# Generated by Django 2.2.5 on 2019-10-29 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20191029_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toolbox',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='toolbox',
            name='time_update',
        ),
        migrations.AddField(
            model_name='toolbox',
            name='avaiable_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='toolbox',
            name='rent_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='toolbox',
            name='time_add',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
