# Generated by Django 2.2.5 on 2019-10-31 11:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20191029_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolbox',
            name='current_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 10, 31, 11, 48, 57, 878188, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
