# Generated by Django 2.2.5 on 2019-10-31 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_toolbox_current_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolbox',
            name='current_time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
