# Generated by Django 2.2.5 on 2019-10-31 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_auto_20191031_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toolbox',
            name='current_time',
        ),
    ]
